# Site identity
name: KirranRH
description: Testing Jekyll â€“ accessibility experiments

# Avatar image
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# URL settings (safe defaults)
baseurl: "/jekyll-now"
url: "https://kirranrh.github.io"

# Blog URL style
permalink: /:title/
